vstup = input("Jak na tebe volají? ")
print("Ahoj ", end='')
print(vstup, end='')
print(", já jsem Počítač")
print()
vstup = input("Ukážu Ti, jak umím mocnit. Zadej mi číslo: ")
cislo = int(vstup)
print("Druhá mocnina Tvého čísla (", end='')
print(cislo, end='')
print("*", end='')
print(cislo, end='')
print(") je ", end='')
print(cislo * cislo)
